[package]
name = "ordered-vecmap"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "An ordered map based on vectors and binary search"
repository = "https://github.com/Nugine/ordered-vecmap"
readme = "README.md"
documentation = "https://docs.rs/ordered-vecmap"
categories = ["data-structures"]
keywords = ["ordered", "map"]

[dev-dependencies]
criterion = "0.3.5"
rand = "0.8.4"

[[bench]]
name = "maps"
harness = false
